import type { DecisionStep, Domain, Pattern, Subdomain } from "../types/pattern";

const p = (
  name: string,
  domain: Domain,
  aliases: string[],
  idea: string,
  useWhen: string[],
  avoidWhen: string[],
  tradeoff: string,
  frameworks: string[],
  subdomain?: Subdomain,
): Pattern => ({ name, domain, aliases, idea, useWhen, avoidWhen, tradeoff, frameworks, subdomain });

export const patterns: Pattern[] = [
  p("ReAct", "Denken", ["Reason + Act", "Thought-Action-Observation Loop"], "Der Agent wechselt iterativ zwischen Reasoning, Tool-Aufruf und Beobachtung.", ["Tool-Use ist nötig", "Pfad ist nicht vorab planbar", "Tool-Ergebnisse verändern den nächsten Schritt"], ["Plan ist bekannt", "LLM-Calls sind streng limitiert", "Reine Generierung reicht"], "Hohe Adaptivität gegen höheren Call-Aufwand.", ["LangGraph", "OpenAI Agents SDK", "Microsoft Agent Framework", "Google ADK", "AutoGen / AG2", "CrewAI"]),
  p("Plan-and-Execute", "Denken", ["Planner-Executor", "Plan then Act"], "Ein Agent erzeugt zuerst einen Plan und führt die Schritte danach kontrolliert aus.", ["Ziel ist zerlegbar", "Zwischenstände sollen prüfbar sein", "Steuerbarkeit ist wichtig"], ["Umgebung ist stark dynamisch", "Tool-Ergebnisse können Plan kippen", "Planungsaufwand ist zu hoch"], "Bessere Struktur gegen Risiko veralteter Pläne.", ["LangGraph", "CrewAI", "Google ADK", "Microsoft Agent Framework", "OpenAI Agents SDK"]),
  p("ReWOO", "Denken", ["Reasoning without Observation", "Planner-Solver Pattern"], "Tool-Aufrufe werden vorab geplant, ausgeführt und gesammelt ausgewertet.", ["Tool-Aufrufe sind erkennbar", "LLM-Calls sollen sinken", "Zwischenbeobachtungen verzweigen kaum"], ["Tool-Ergebnisse verzweigen stark", "Fehlerbehandlung pro Schritt ist kritisch", "Interaktive Reaktion ist nötig"], "Niedrigere LLM-Kosten gegen geringere Adaptivität.", ["LangGraph", "Google ADK", "OpenAI Agents SDK"]),
  p("Reflexion", "Denken", ["Self-Reflection", "Self-Critique"], "Der Agent bewertet eigene Zwischenergebnisse und verbessert sie iterativ.", ["Qualität ist wichtiger als Latenz", "Fehler können durch Selbstprüfung auffallen", "Iteration ist möglich"], ["Externe Validierung reicht", "Selbstbewertung ist unzuverlässig", "Budget ist eng"], "Mehr Qualität gegen zusätzliche Tokens.", ["LangGraph", "AutoGen / AG2", "Microsoft Agent Framework", "Google ADK", "CrewAI"]),
  p("Tree of Thoughts", "Denken", ["ToT", "Branching Reasoning"], "Mehrere Reasoning-Pfade werden als Baum exploriert und bewertet.", ["Mehrere Lösungswege existieren", "Frühe Entscheidungen wirken stark", "Suchraum ist bewertbar"], ["Aufgabe ist direkt lösbar", "Kosten müssen niedrig bleiben", "Bewertung der Äste ist unklar"], "Breitere Exploration gegen stark steigenden Tokenaufwand.", ["LangGraph", "AutoGen / AG2", "Google ADK"]),
  p("Self-Consistency", "Denken", ["Majority Reasoning", "Sample-and-Vote"], "Mehrere unabhängige Reasoning-Ausgaben werden per Konsens zusammengeführt.", ["Robustheit ist wichtig", "Ergebnis ist abstimmbar", "Modellvarianz ist hilfreich"], ["Objektive Validierung verfügbar ist", "Kosten streng limitiert sind", "Mehrheit falsche Sicherheit erzeugt"], "Robustere Antworten gegen mehrfachen Inferenzaufwand.", ["Anthropic Cookbook", "Google ADK", "LangGraph", "Microsoft Agent Framework"]),
  p("CodeAct", "Denken", ["Code as Action", "Executable Reasoning"], "Der Agent nutzt ausführbaren Code als Handlungs- und Reasoning-Medium.", ["Berechnung nötig ist", "Zwischenergebnisse reproduzierbar sein sollen", "Programmatische Logik hilft"], ["Ausführung nicht sandboxed ist", "Aufgabe rein sprachlich ist", "Codeausführung mehr Risiko erzeugt"], "Präzision gegen Sandbox- und Laufzeitaufwand.", ["OpenAI Agents SDK", "AutoGen / AG2", "Microsoft Agent Framework", "LangGraph", "Google ADK"]),

  p("Sequential Pipeline (Prompt Chaining)", "Ablauf", ["Prompt Chaining", "Linear Workflow"], "Mehrere Schritte laufen in fester Reihenfolge.", ["Aufgabe zerfällt klar in Phasen", "Zwischenprodukte sind prüfbar", "Kontrolle ist wichtiger als Autonomie"], ["Ablauf verzweigt stark", "Ergebnisse erzeugen neue Ziele", "Parallelisierung liegt nahe"], "Hohe Verständlichkeit gegen geringe Flexibilität.", ["Anthropic Cookbook", "CrewAI", "Google ADK", "Microsoft Agent Framework", "AWS Strands"]),
  p("Routing", "Ablauf", ["Classifier Router", "Intent Routing"], "Eine Anfrage wird an den passenden Pfad, Prompt, Agenten oder Tool geleitet.", ["Anfrageklassen verschiedene Behandlung brauchen", "Spezialisierte Prompts existieren", "Fehlpfade teuer sind"], ["Alle Aufgaben denselben Ablauf nutzen", "Klassifikation instabil ist", "Routinglogik zu komplex wird"], "Präzisere Behandlung gegen Fehlrouting-Risiko.", ["Anthropic Cookbook", "LangGraph", "Google ADK", "Microsoft Agent Framework", "AWS Strands"]),
  p("Parallelization (Sectioning)", "Ablauf", ["Sectioned Parallelism", "Fan-out by Segment"], "Unabhängige Teilbereiche werden parallel bearbeitet und zusammengeführt.", ["Eingabe segmentierbar ist", "Teilaufgaben unabhängig sind", "Latenz sinken soll"], ["Starke Abhängigkeiten bestehen", "Zusammenführung schwierig ist", "Globale Konsistenz wichtiger ist"], "Geringere Latenz gegen Integrationsaufwand.", ["Anthropic Cookbook", "Google ADK", "Microsoft Agent Framework", "AWS Strands", "LangGraph"]),
  p("Parallelization (Voting)", "Ablauf", ["Voting Parallelism", "Ensemble Voting"], "Mehrere Läufe bearbeiten dieselbe Aufgabe und ein Aggregator entscheidet.", ["Robustheit wichtig ist", "Antworten bewertbar sind", "Modellvarianz genutzt werden soll"], ["Ergebnis objektiv validierbar ist", "Antwort nicht aggregierbar ist", "Latenz streng begrenzt ist"], "Höhere Robustheit gegen mehrfachen Aufwand.", ["Anthropic Cookbook", "Google ADK", "Microsoft Agent Framework", "LangGraph"]),
  p("Loop", "Ablauf", ["Control Loop", "Retry Loop"], "Schritte werden bis zu Abbruchbedingung, Qualitätsziel oder Budget wiederholt.", ["Ergebnis verbessert werden kann", "Validierung Wiederholung auslöst", "Tool-Ergebnisse Iteration erfordern"], ["Keine stabile Abbruchbedingung existiert", "Kosten steigen unkontrolliert", "Fehler sich verstärken"], "Adaptive Verbesserung gegen Risiko teurer Schleifen.", ["LangGraph", "CrewAI Flows", "Microsoft Agent Framework", "Google ADK", "AWS Strands"]),
  p("Evaluator-Optimizer (Generator-Critic)", "Ablauf", ["Generator-Critic", "Critique and Revise"], "Ein Generator erstellt, ein Evaluator bewertet, der Generator verbessert.", ["Qualitätskriterien formulierbar sind", "Iteration messbar ist", "Komplexe Ausgaben geprüft werden"], ["Evaluator unzuverlässig ist", "Schema-Validation reicht", "Budget keine Mehrfachläufe erlaubt"], "Bessere Qualität gegen Bewertungskomplexität.", ["Anthropic Cookbook", "Google ADK", "LangGraph", "AutoGen / AG2", "Microsoft Agent Framework"]),
  p("Iterative Refinement", "Ablauf", ["Revise Loop", "Draft-Improve"], "Ein Ergebnis wird über kontrollierte Revisionen verbessert.", ["Qualität graduell steigt", "Feedback verfügbar ist", "Zwischenstände wichtig sind"], ["Ein Schritt reicht", "Revisionen ohne klares Signal erfolgen", "Wiederholung Drift erzeugt"], "Verbesserte Qualität gegen längere Laufzeit.", ["Google ADK", "LangGraph", "CrewAI Flows", "Microsoft Agent Framework"]),
  p("Orchestrator-Workers", "Ablauf", ["Coordinator-Workers", "Manager-Worker"], "Ein Orchestrator zerlegt Aufgaben dynamisch und weist Worker zu.", ["Teilaufgaben erst zur Laufzeit erkennbar sind", "Worker spezialisiert sind", "Aggregation zentral bleibt"], ["Statischer Workflow reicht", "Worker keine klare Verantwortung haben", "Orchestrator Engpass wird"], "Flexible Delegation gegen Koordinationsaufwand.", ["Anthropic Cookbook", "LangGraph", "CrewAI", "Google ADK", "Microsoft Agent Framework", "AWS Strands"]),
  p("Map-Reduce", "Ablauf", ["Fan-out/Fan-in", "Batch Decomposition"], "Eine Aufgabe wird auf unabhängige Einheiten gemappt und aggregiert.", ["Große Eingaben in Chunks zerlegbar sind", "Aggregation klar ist", "Durchsatz wichtig ist"], ["Globale Abhängigkeiten bestehen", "Reduktion verlustreich wäre", "Zentraler Kontext nötig ist"], "Gute Skalierung gegen inkonsistente Teilresultate.", ["LangGraph", "AWS Strands", "Google ADK", "Microsoft Agent Framework", "Anthropic Cookbook"]),

  p("Supervisor", "Zusammenarbeit", ["Manager Agent", "Coordinator Agent"], "Ein zentraler Agent entscheidet, wer als Nächstes arbeitet.", ["Zentrale Kontrolle zählt", "Spezialisten koordiniert werden", "Aufgaben dynamisch delegiert werden"], ["Dezentrale Kooperation nötig ist", "Supervisor Engpass wird", "Routing ausreicht"], "Klare Kontrolle gegen Koordinationsengpass.", ["LangGraph", "CrewAI", "Microsoft Agent Framework", "Google ADK", "AWS Strands"]),
  p("Hierarchical Supervisor", "Zusammenarbeit", ["Multi-Level Supervisor", "Manager Hierarchy"], "Supervisoren organisieren Agenten in Ebenen oder Teams.", ["Agentenzahl groß wird", "Domänen getrennt werden", "Lokale Entscheidungen zusammengeführt werden"], ["Wenige Agenten reichen", "Kommunikationswege kurz bleiben sollen", "Verantwortlichkeiten unscharf sind"], "Skalierbare Organisation gegen längere Entscheidungswege.", ["CrewAI", "LangGraph", "Google ADK", "Microsoft Agent Framework"]),
  p("Handoff", "Zusammenarbeit", ["Transfer of Control", "Agent Transfer"], "Ein Agent übergibt Kontrolle und Kontext an einen anderen Agenten.", ["Zuständigkeit klar wechselt", "Nutzerinteraktion wechseln soll", "Tool-Grenzen gelten"], ["Mehrere Agents gleichzeitig beitragen", "Kontrolle zentral bleiben muss", "Kontextübergabe unklar ist"], "Klare Übergabe gegen Kontextverlust.", ["OpenAI Agents SDK", "Microsoft Agent Framework", "LangGraph", "Google ADK"]),
  p("Swarm", "Zusammenarbeit", ["Decentralized Agents", "Peer Agent Swarm"], "Agenten koordinieren dezentral über Regeln, Nachrichten oder Ziele.", ["Dezentrale Exploration gewünscht ist", "Aufgaben adaptiv verteilt werden", "Zentrale Steuerung zu starr ist"], ["Strenge Nachvollziehbarkeit nötig ist", "Nachrichtenflut begrenzt werden muss", "Klare Verantwortung wichtiger ist"], "Hohe Anpassungsfähigkeit gegen geringe Vorhersagbarkeit.", ["LangGraph Swarm", "AWS Strands Swarm", "Microsoft Agent Framework", "AutoGen / AG2"]),
  p("Group Chat", "Zusammenarbeit", ["Multi-Agent Chat", "Round-Robin Conversation"], "Mehrere Agents kommunizieren in einem gemeinsamen Gesprächsraum.", ["Perspektiven zusammengeführt werden", "Diskussion Teil der Lösung ist", "Rollen flexibel interagieren"], ["Determinismus wichtiger ist", "Tokenverbrauch niedrig bleiben muss", "Verantwortlichkeiten streng getrennt sind"], "Reichhaltige Interaktion gegen hohe Kosten.", ["AutoGen / AG2", "Microsoft Agent Framework", "Google ADK", "LangGraph"]),
  p("Multi-Agent Debate", "Zusammenarbeit", ["Debate", "Adversarial Agents"], "Agenten prüfen unterschiedliche Positionen vor einer Entscheidung.", ["Fragestellung kontrovers ist", "Gegenargumente Fehler sichtbar machen", "Entscheidung geprüft werden soll"], ["Faktenlage einfach validierbar ist", "Debatte Scheinkonflikte erzeugt", "Tokenbudget knapp ist"], "Bessere Prüfung gegen Aufwand.", ["AutoGen / AG2", "LangGraph", "Microsoft Agent Framework", "Google ADK"]),
  p("Magentic", "Zusammenarbeit", ["Magentic-One", "Composite Orchestration"], "Ein Verbund spezialisierter Agenten löst offene Aufgaben mit Planning, Task Ledger und Delegation.", ["Aufgaben offen sind", "Spezialisten koordiniert handeln", "Autonomie über längere Horizonte nötig ist"], ["Ein einfacher Workflow reicht", "Jeder Schritt deterministisch sein muss", "Betriebskosten eng begrenzt sind"], "Große Aufgabenabdeckung gegen hohe Komplexität.", ["Microsoft Agent Framework", "AutoGen / AG2 Magentic-One", "LangGraph"]),
  p("Blackboard", "Zusammenarbeit", ["Shared Workspace", "Shared State Coordination"], "Agents koordinieren über eine gemeinsame Zustandsfläche.", ["Viele Agents asynchron beitragen", "Gemeinsamer Zustand wichtiger ist als Chat", "Zwischenergebnisse persistent sein sollen"], ["Lineare Kontrolle nötig ist", "Zustandskonsistenz ungesichert ist", "Chat-Kontext reicht"], "Entkoppelte Zusammenarbeit gegen State-Management-Aufwand.", ["LangGraph", "AWS Strands", "Microsoft Agent Framework", "AutoGen / AG2"]),
  p("Contract Net", "Zusammenarbeit", ["Task Bidding", "Contract Net Protocol"], "Ein Agent schreibt Aufgaben aus und andere Agenten bieten darauf.", ["Aufgaben dynamisch verteilt werden", "Agenten unterschiedliche Kapazitäten haben", "Auswahlkriterien explizit sind"], ["Delegation fest vorgegeben ist", "Bietlogik zu teuer ist", "Selbstauskünfte unzuverlässig sind"], "Flexible Verteilung gegen Aushandlungsaufwand.", ["LangGraph", "AutoGen / AG2", "Microsoft Agent Framework"]),
  p("Market-based", "Zusammenarbeit", ["Market Mechanism", "Price-based Coordination"], "Agenten koordinieren Ressourcen über Preise, Budgets oder Nutzen.", ["Ressourcen knapp sind", "Priorisierung über Kosten erfolgen soll", "Viele Agenten konkurrieren"], ["Compliance zentrale Vorgaben braucht", "Nutzenfunktion unklar ist", "Kein Ressourcenkonflikt besteht"], "Skalierbare Allokation gegen schwieriges Anreizdesign.", ["LangGraph", "AWS Strands", "AutoGen / AG2"]),
  p("Agents-as-Tools", "Zusammenarbeit", ["Callable Agents", "Specialist-as-Tool"], "Ein Agent ruft andere Agenten wie Tools mit klarer Schnittstelle auf.", ["Spezialisten gekapselt genutzt werden", "Hauptagent Kontrolle behält", "Tool-Sets getrennt werden"], ["Gleichberechtigte Kooperation nötig ist", "Spezialisten lange Autonomie brauchen", "Schnittstellen instabil sind"], "Gute Kapselung gegen begrenzte Eigenständigkeit.", ["AWS Strands", "OpenAI Agents SDK", "LangGraph", "Microsoft Agent Framework", "Google ADK"]),
  p("Graph-based Orchestration", "Zusammenarbeit", ["Agent Graph", "State Graph Orchestration"], "Agenten, Tools und Kontrollübergänge werden als expliziter Graph modelliert.", ["Koordination testbar sein soll", "Zyklen und Handoffs modelliert werden", "Komplexe Flüsse stabil laufen"], ["Linearer Workflow reicht", "Graphpflege zu teuer ist", "Emergenz wichtiger ist"], "Hohe Steuerbarkeit gegen Modellierungsaufwand.", ["LangGraph", "AWS Strands Graph", "Microsoft Agent Framework", "Google ADK", "CrewAI Flows"]),
];

export const systemPatterns: Pattern[] = [
  p("Conversational Memory", "Systembetrieb", ["Chat History", "Conversation Buffer"], "Gesprächshistorie bleibt für spätere Turns verfügbar.", ["Nutzerkontext erhalten bleibt", "Bezugnahmen erwartet werden", "Gesprächsfluss wichtig ist"], ["Datenschutz Speicherung verbietet", "Historie Tokens verschwendet", "Aufgaben zustandslos sind"], "Besserer Kontext gegen Datenschutz- und Tokenaufwand.", ["LangChain", "LangGraph", "OpenAI Agents SDK", "Microsoft Agent Framework"], "Memory Architecture"),
  p("Episodic Memory", "Systembetrieb", ["Experience Memory", "Task Episode Store"], "Abgeschlossene Interaktionen werden als Episoden gespeichert.", ["Frühere Fälle hilfreich sind", "Aufgaben wiederkehren", "Zeit, Ziel und Ergebnis relevant sind"], ["Fälle veraltet sind", "Personendaten problematisch sind", "Semantische Wissensbasis reicht"], "Erfahrungswissen gegen Kurationsaufwand.", ["LangGraph", "AutoGen / AG2", "Microsoft Agent Framework", "CrewAI"], "Memory Architecture"),
  p("Semantic Memory", "Systembetrieb", ["Knowledge Memory", "Long-Term Knowledge"], "Dauerhaftes Wissen wird unabhängig von Gesprächen gespeichert.", ["Domänenwissen langfristig genutzt wird", "Fakten wiederverwendet werden", "Retrieval über Sitzungen nötig ist"], ["Wissen schnell veraltet", "Governance fehlt", "Prompt-Kontext reicht"], "Wiederverwendbares Wissen gegen Qualitätsrisiken.", ["LangChain", "LangGraph", "OpenAI Agents SDK", "Google ADK"], "Memory Architecture"),
  p("Working Memory / Scratchpad", "Systembetrieb", ["Scratchpad", "Task State"], "Temporärer Arbeitszustand hält Zwischenschritte und Tool-Ergebnisse.", ["Mehrschrittige Aufgaben Zustand brauchen", "Tool-Ergebnisse referenziert werden", "Ausführung nachvollziehbar sein soll"], ["Aufgabe atomar ist", "Zwischengedanken nicht gespeichert werden dürfen", "Persistenz über Läufe nötig ist"], "Steuerbarkeit gegen State-Verwaltung.", ["LangGraph State", "OpenAI Agents SDK", "Microsoft Agent Framework"], "Memory Architecture"),
  p("Vector Memory", "Systembetrieb", ["Vector Store Memory", "RAG Memory"], "Inhalte werden per Embeddings semantisch abgerufen.", ["Große Wissensmengen gesucht werden", "Wortlaut variieren kann", "RAG benötigt wird"], ["Exakte relationale Abfragen zentral sind", "Aktualität schwer kontrollierbar ist", "Ähnlichkeit falsche Treffer erzeugt"], "Flexibles Retrieval gegen Ranking-Probleme.", ["LangChain", "LangGraph", "OpenAI Vector Stores"], "Memory Architecture"),
  p("Graph Memory", "Systembetrieb", ["Knowledge Graph Memory", "Entity-Relation Memory"], "Entitäten und Beziehungen werden als Graph gespeichert.", ["Beziehungen entscheidend sind", "Herkunft erklärbar sein muss", "Agenten über Fakten navigieren"], ["Unstrukturierter Abruf genügt", "Graphschema unklar ist", "Pflege zu teuer ist"], "Erklärbarkeit gegen Modellierungsaufwand.", ["LangGraph", "Microsoft Agent Framework", "Google ADK"], "Memory Architecture"),
  p("Compressed Context Memory", "Systembetrieb", ["Context Compression", "Rolling Summary"], "Langer Kontext wird verdichtet, damit Relevantes im Kontextfenster bleibt.", ["Gespräche lange laufen", "Tokenbudget begrenzt ist", "Alte Information relevant bleibt"], ["Wortlaut exakt bleiben muss", "Zusammenfassung Verlust erzeugt", "Kurze Kontexte reichen"], "Mehr nutzbarer Verlauf gegen Detailverlust.", ["LangChain", "LangGraph", "AutoGen / AG2"], "Memory Architecture"),

  p("Function Calling", "Systembetrieb", ["Tool Calling", "Structured Tool Use"], "Das Modell ruft definierte Funktionen mit validierbaren Argumenten auf.", ["Externe Aktionen kontrolliert eingebunden werden", "Argumente validierbar sein müssen", "Tool-Use beobachtbar bleibt"], ["Aufgabe ohne Aktion lösbar ist", "Tool-Schema instabil ist", "Freitext besser passt"], "Kontrolle gegen Schema-Aufwand.", ["OpenAI Agents SDK", "LangGraph", "Microsoft Agent Framework"], "Tool Integration"),
  p("Tool Registry", "Systembetrieb", ["Capability Catalog", "Tool Catalog"], "Tools werden mit Schema, Beschreibung und Berechtigungen registriert.", ["Viele Tools verwaltet werden", "Versionierung wichtig ist", "Tools von mehreren Agenten genutzt werden"], ["Wenige statische Tools existieren", "Registry nicht gepflegt wird", "Beschreibungen schlechte Auswahl erzeugen"], "Governance gegen Pflegeaufwand.", ["OpenAI Agents SDK", "LangGraph", "Google ADK"], "Tool Integration"),
  p("MCP (Model Context Protocol)", "Systembetrieb", ["MCP-based Tool Integration", "MCP Server"], "Tools und Kontext werden über MCP standardisiert verfügbar gemacht.", ["Tools frameworkübergreifend nutzbar sein sollen", "Lokale Systeme angebunden werden", "Kontextzugriff standardisiert wird"], ["Direkte SDK-Integration reicht", "Sicherheitsmodell ungeklärt ist", "Protokollbetrieb zu komplex ist"], "Interoperabilität gegen Betriebsaufwand.", ["OpenAI Agents SDK", "LangGraph", "Claude Desktop"], "Tool Integration"),
  p("Adapter Pattern", "Systembetrieb", ["Tool Adapter", "API Wrapper"], "Externe APIs werden in stabile agentengerechte Schnittstellen übersetzt.", ["APIs uneinheitlich sind", "Agenten einfache Tool-Verträge brauchen", "Fehlerlogik gekapselt werden soll"], ["Native SDKs passen", "Adapter nur Durchreichung wäre", "Abstraktion Semantik versteckt"], "Stabilität gegen Wartungsschicht.", ["OpenAI Agents SDK", "LangGraph", "Google ADK"], "Tool Integration"),
  p("Capability Routing", "Systembetrieb", ["Tool Selection", "Skill Routing"], "Anfragen werden anhand benötigter Fähigkeiten weitergeleitet.", ["Viele Fähigkeiten verfügbar sind", "Auswahl Policy braucht", "Fehlende Fähigkeiten erkannt werden müssen"], ["Toolauswahl trivial ist", "Beschreibungen unpräzise sind", "Routing nicht getestet wird"], "Flexibilität gegen Fehlzuordnung.", ["LangGraph", "OpenAI Agents SDK", "Microsoft Agent Framework"], "Tool Integration"),
  p("Permission-scoped Tools", "Systembetrieb", ["Scoped Tools", "Permissioned Tools"], "Tools werden pro Agent, Aufgabe oder Lauf minimal berechtigt.", ["Tools sensitive Aktionen ausführen", "Agenten unterschiedliche Rechte brauchen", "Compliance relevant ist"], ["Aktionen unkritisch sind", "Rechte nicht modellierbar sind", "Fragmentierung Bedienbarkeit senkt"], "Sicherheit gegen Verwaltungsaufwand.", ["OpenAI Agents SDK", "Microsoft Agent Framework", "LangGraph"], "Tool Integration"),

  p("Actor Model", "Systembetrieb", ["Actor-based Runtime", "Agent Actors"], "Komponenten kapseln Zustand und kommunizieren über Nachrichten.", ["Nebenläufigkeit wichtig ist", "Agenten eigenen Zustand besitzen", "Skalierung über Einheiten erfolgen soll"], ["Synchroner Workflow reicht", "Nachrichtenmodell unnötig ist", "Globale Transaktionen zentral sind"], "Isolation gegen Fehlersemantik.", ["Microsoft Agent Framework", "AutoGen / AG2", "AWS Strands"], "Runtime Architecture"),
  p("Event-driven Choreography", "Systembetrieb", ["Event Choreography", "Event-driven Agents"], "Komponenten reagieren auf Ereignisse statt zentrale Steuerung.", ["Systeme lose gekoppelt sein sollen", "Ereignisse aus mehreren Quellen eintreffen", "Erweiterbarkeit wichtig ist"], ["Globaler Ablauf streng kontrolliert werden muss", "Eventual Consistency nicht akzeptabel ist", "Tracing fehlt"], "Entkopplung gegen globale Kontrollschwierigkeit.", ["AWS Strands", "Microsoft Agent Framework", "LangGraph"], "Runtime Architecture"),
  p("Saga / Compensation", "Systembetrieb", ["Saga Pattern", "Compensating Action"], "Mehrschrittige Aktionen werden durch Ausgleichsschritte abgesichert.", ["Nebenwirkungen entstehen", "Verteilte Transaktionen fehlen", "Rücknahme fachlich möglich ist"], ["Aktionen nicht kompensierbar sind", "Atomare Konsistenz erforderlich ist", "Freigabe Fehler besser verhindert"], "Robustheit gegen Kompensationslogik.", ["AWS Strands Workflow", "Microsoft Agent Framework", "LangGraph"], "Runtime Architecture"),
  p("Workflow DAG / Durable Execution", "Systembetrieb", ["Durable Workflow", "DAG Orchestration"], "Workflows laufen als persistente Ausführungsgraphen mit Retry und Resume.", ["Läufe lange dauern", "Zustände robust verwaltet werden", "Produktion Nachvollziehbarkeit verlangt"], ["Aufgaben kurz sind", "Persistenz unnötig wäre", "Graphmodell nicht passt"], "Produktionsrobustheit gegen Infrastrukturaufwand.", ["LangGraph", "AWS Strands Workflow", "Google ADK"], "Runtime Architecture"),
  p("Checkpointing / Resumability", "Systembetrieb", ["State Checkpointing", "Resume from State"], "Ausführungszustand wird gespeichert, damit Läufe fortgesetzt werden können.", ["Agentenläufe lang sind", "Externe Systeme ausfallen können", "Manuelle Prüfung nötig ist"], ["Schritte billig wiederholbar sind", "Sensitive Daten unnötig persistiert würden", "Wiederaufnahme fachlich nicht sinnvoll ist"], "Ausfallsicherheit gegen Speicheraufwand.", ["LangGraph", "Microsoft Agent Framework", "AWS Strands Workflow"], "Runtime Architecture"),
  p("Pub/Sub Agent Mesh", "Systembetrieb", ["Publish / Subscribe", "Message Bus Coordination"], "Agenten kommunizieren über Topics, Events oder Nachrichtenbusse.", ["Viele Agenten lose gekoppelt werden", "Ereignisse mehrere Empfänger haben", "Erweiterbarkeit wichtig ist"], ["Direkter Aufruf reicht", "Zustellung ungeklärt ist", "Beobachtbarkeit fehlt"], "Entkopplung gegen Debugging-Aufwand.", ["AWS", "Microsoft Agent Framework", "LangGraph"], "Runtime Architecture"),

  p("Human-in-the-Loop Approval Gate", "Systembetrieb", ["HITL", "Human Approval"], "Menschen geben kritische Schritte frei.", ["Aktionen irreversible Folgen haben", "Compliance menschliche Entscheidung verlangt", "Unsicherheit sichtbar werden soll"], ["Niedrigrisiko-Aktionen automatisch laufen können", "Freigaben symbolisch sind", "Latenz Prüfung ausschließt"], "Kontrolle gegen langsamere Abläufe.", ["Google ADK", "OpenAI Agents SDK", "LangGraph"], "Governance & Safety"),
  p("Output Validation / Schema Enforcement", "Systembetrieb", ["Structured Output Validation", "Schema Validation"], "Modellantworten werden gegen Schemata und Regeln validiert.", ["Downstream-Systeme strukturierte Daten erwarten", "Fehler früh erkannt werden", "Automatisierte Verarbeitung folgt"], ["Freiformtext Ziel ist", "Schema Antwort einschränkt", "Validierung fachlich blind ist"], "Zuverlässigkeit gegen weniger Ausdrucksfreiheit.", ["OpenAI Structured Outputs", "LangGraph", "Google ADK"], "Governance & Safety"),
  p("Sandbox Execution", "Systembetrieb", ["Isolated Execution", "Code Sandbox"], "Code läuft in einer isolierten Umgebung.", ["Agenten Code oder Shell ausführen", "Untrusted Inputs verarbeitet werden", "Seiteneffekte begrenzt werden müssen"], ["Keine Ausführung stattfindet", "Sandbox nicht kontrolliert ist", "Geprüfte Tools besser passen"], "Sicherheit gegen Infrastrukturaufwand.", ["OpenAI Code Interpreter", "AutoGen / AG2", "LangGraph"], "Governance & Safety"),
  p("Least Privilege Agent", "Systembetrieb", ["Minimal Permission Agent", "Scoped Agent"], "Jeder Agent erhält nur notwendige Tools, Daten und Rechte.", ["Vertrauenszonen getrennt sind", "Sensitive Daten beteiligt sind", "Sicherheitsgrenzen sichtbar sein sollen"], ["Rollen unklar sind", "Berechtigungsmodell Pflege verhindert", "Einschränkung Kernfunktionen blockiert"], "Geringere Angriffsfläche gegen Rollenaufwand.", ["OpenAI Agents SDK", "Microsoft Agent Framework", "LangGraph"], "Governance & Safety"),
  p("Audit Trail", "Systembetrieb", ["Execution Log", "Decision Log"], "Entscheidungen, Tool-Aufrufe und Freigaben werden protokolliert.", ["Compliance Nachvollziehbarkeit verlangt", "Agenten externe Aktionen auslösen", "Analysen möglich sein sollen"], ["Logs sensitive Daten ungeschützt speichern", "Aufbewahrung ungeklärt ist", "Logging Rauschen erzeugt"], "Nachvollziehbarkeit gegen Datenschutzaufwand.", ["OpenAI Agents SDK Tracing", "LangSmith", "Google ADK"], "Governance & Safety"),
  p("Multimodal Guardrails", "Systembetrieb", ["Multimodal Safety Filters", "Media Validation"], "Text, Bild, Audio oder Video werden modalitätsspezifisch geprüft.", ["Agenten multimodale Daten verarbeiten", "Medien Compliance-Risiken tragen", "Mehrere Modalitäten kontrolliert werden"], ["System rein textuell bleibt", "Guardrails Modalitäten nicht abdecken", "Prüfung Inhalte blockiert"], "Sicherheit gegen Latenz und Fehlklassifikation.", ["OpenAI Moderation", "Azure AI Content Safety", "AWS Bedrock Guardrails"], "Governance & Safety"),

  p("Distributed Tracing", "Systembetrieb", ["Agent Tracing", "End-to-End Trace"], "Agentenläufe und Tool-Aufrufe werden als zusammenhängende Traces sichtbar.", ["Mehrere Komponenten beteiligt sind", "Fehlerursachen analysiert werden", "Produktionsbetrieb beobachtet wird"], ["System minimal lokal bleibt", "Trace-Daten Datenschutzrisiken erzeugen", "Telemetriekosten überwiegen"], "Diagnosefähigkeit gegen Telemetrieaufwand.", ["OpenAI Agents SDK Tracing", "LangSmith", "AWS X-Ray"], "Observability & Evaluation"),
  p("Token / Cost Tracking", "Systembetrieb", ["Usage Tracking", "Cost Observability"], "Tokenverbrauch und Kosten werden pro Lauf, Agent oder Workflow gemessen.", ["Kosten begrenzt werden müssen", "Agenten autonom Schleifen ausführen", "Patterns optimiert werden sollen"], ["Budget irrelevant ist", "Messdaten nicht handlungsrelevant sind", "Kosten außerhalb nicht erfassbar sind"], "Budgetkontrolle gegen Messaufwand.", ["OpenAI Usage APIs", "LangSmith", "AWS Cost"], "Observability & Evaluation"),
  p("LLM-as-Judge", "Systembetrieb", ["Large Language Model as Judge", "AI Evaluator"], "Ein Modell bewertet Ausgaben anhand von Kriterien oder Rubrics.", ["Bewertung skalieren muss", "Qualitätskriterien sprachlich formulierbar sind", "Regressionen erkannt werden sollen"], ["Objektive Tests verfügbar sind", "Judge denselben Bias hat", "Hohe rechtliche Verbindlichkeit nötig ist"], "Skalierbare Bewertung gegen Kalibrierungsbedarf.", ["LangSmith", "OpenAI Evals", "Google ADK"], "Observability & Evaluation"),
  p("Integration Tests für Agents", "Systembetrieb", ["Agent Integration Tests", "Scenario Tests"], "Agenten werden über Szenarien, Tools, Speicher und Kontrollflüsse getestet.", ["Agenten produktionsnah handeln", "Tool- und Workflow-Grenzen geprüft werden", "Regressionen sichtbar werden"], ["Nur ein Prompt exploriert wird", "Bewertung nicht deterministisch ist", "Testumgebung externe Systeme gefährdet"], "Betriebssicherheit gegen Testaufwand.", ["LangSmith", "OpenAI Evals", "Microsoft Agent Framework"], "Observability & Evaluation"),
];

export const allPatterns = [...patterns, ...systemPatterns];

export const domains: Array<Domain | "Alle"> = [
  "Alle",
  "Denken",
  "Ablauf",
  "Zusammenarbeit",
  "Systembetrieb",
];

export const decisionSteps: DecisionStep[] = [
  {
    question: "Reicht ein einzelner Prompt mit gutem Prompt-Engineering?",
    yes: "Direkter Modell-Call. Stop.",
    no: "Prüfen, ob externe Daten, Tools oder mehr Struktur nötig sind.",
    recommendation: ["Direct Model Call", "Self-Consistency", "Reflexion"],
  },
  {
    question: "Braucht es externe Interaktion oder Datenzugriff?",
    yes: "Tool-enabled Design prüfen: Function Calling, ReAct oder MCP.",
    no: "Reasoning Pattern prüfen: Self-Consistency, Tree of Thoughts oder Reflexion.",
    recommendation: ["Function Calling", "ReAct", "MCP (Model Context Protocol)"],
  },
  {
    question: "Ist der Ablauf vorhersagbar?",
    yes: "Workflow-Pattern aus Domäne Ablauf wählen.",
    no: "Agentisches Design prüfen.",
    recommendation: ["Sequential Pipeline", "Routing", "Map-Reduce"],
  },
  {
    question: "Reicht ein autonomer Agent?",
    yes: "Single Agent mit ReAct oder Plan-and-Execute ist meist ausreichend.",
    no: "Zusammenarbeit modellieren.",
    recommendation: ["ReAct", "Plan-and-Execute", "Supervisor"],
  },
  {
    question: "Sind echte Spezialisten nötig?",
    yes: "Multi-Agent-Pattern aus Domäne Zusammenarbeit wählen.",
    no: "Single Agent mit gutem Tool-Design und Capability Routing bevorzugen.",
    recommendation: ["Handoff", "Supervisor", "Agents-as-Tools"],
  },
  {
    question: "Müssen mehrere Agents autonom ohne festen Plan kooperieren?",
    yes: "Magentic, Group Chat oder Blackboard prüfen.",
    no: "Supervisor oder Handoff reichen meist.",
    recommendation: ["Magentic", "Group Chat", "Blackboard"],
  },
  {
    question: "Geht es in Richtung Production?",
    yes: "Systembetrieb ist verpflichtend: Memory, Runtime, Governance, Observability und Evaluation.",
    no: "Für Prototypen bewusst schlank bleiben und Risiken dokumentieren.",
    recommendation: ["Workflow DAG / Durable Execution", "Human-in-the-Loop Approval Gate", "Distributed Tracing"],
  },
];

export const frameworkRows = [
  ["Anthropic Cookbook", "5 Workflow-Patterns", "Minimal, gut erklärbar"],
  ["LangGraph", "Supervisor, Swarm, Graph-based", "Kontrollierte Graph-Orchestrierung"],
  ["CrewAI", "Sequential, Hierarchical Process, Flows", "Rollen und Prozesse"],
  ["AutoGen / AG2", "GroupChat, Two-Agent-Chat, Nested Chats", "Multi-Agent-Kommunikation"],
  ["Microsoft Agent Framework", "Sequential, Concurrent, Handoff, Magentic", "Breite Orchestrierung"],
  ["Google ADK", "Pipeline, Coordinator, Parallel, HITL, Composite", "Breite Pattern-Abdeckung"],
  ["AWS Strands", "Graph, Swarm, Workflow, Agents-as-Tools", "Agent Runtime und AWS-Integration"],
  ["OpenAI Agents SDK", "Handoff, Tools, Guardrails", "Nahe Modell- und Tool-Integration"],
];

