from __future__ import annotations

from ai_agent_patterns.demos.common import PatternDemo


SPECS: dict[str, PatternDemo] = {
    'evaluator-optimizer': PatternDemo(
        slug='evaluator-optimizer',
        name='Evaluator-Optimizer (Generator-Critic)',
        domain='Ablauf',
        aliases=('Generator-Critic', 'Evaluate-Improve'),
        idea='Ein Generator erzeugt ein Ergebnis, ein Evaluator bewertet es und ein Optimizer verbessert es.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Entwurf generieren', 'Entwurf gegen Rubrik bewerten', 'Bei Bedarf optimierte Version erzeugen'),
        snippet='draft = generator.invoke(prompt)\nscore = evaluator.invoke({"draft": draft, "rubric": rubric})\nanswer = optimizer.invoke({"draft": draft, "score": score})',
    ),
    'iterative-refinement': PatternDemo(
        slug='iterative-refinement',
        name='Iterative Refinement',
        domain='Ablauf',
        aliases=('Draft-Improve', 'Revise Loop'),
        idea='Ein Ergebnis wird über kontrollierte Revisionen schrittweise verbessert.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Entwurf erzeugen', 'Feedback anwenden', 'Finale Version nach Budget oder Qualitätsziel liefern'),
        snippet='draft = generator.invoke(prompt)\nfor _ in range(2):\n    feedback = reviewer.invoke(draft)\n    draft = reviser.invoke({"draft": draft, "feedback": feedback})',
    ),
    'loop': PatternDemo(
        slug='loop',
        name='Loop',
        domain='Ablauf',
        aliases=('Control Loop', 'Retry Loop'),
        idea='Ein Schritt wird bis zu einer Abbruchbedingung wiederholt.',
        frameworks=('LangGraph', 'CrewAI Flows'),
        steps=('Ergebnis erzeugen', 'Qualität oder Status prüfen', 'Bei Bedarf erneut ausführen'),
        snippet='while attempts < max_attempts:\n    draft = worker.invoke(prompt)\n    if validator.invoke(draft).passed:\n        break\n    attempts += 1',
    ),
    'map-reduce': PatternDemo(
        slug='map-reduce',
        name='Map-Reduce',
        domain='Ablauf',
        aliases=('Fan-out/Fan-in', 'Map Aggregate'),
        idea='Viele unabhängige Chunks werden gemappt und anschließend reduziert.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Dokumente oder Einheiten chunken', 'Map-Funktion pro Chunk ausführen', 'Reduce-Funktion aggregiert'),
        snippet='mapped = mapper.batch(split(prompt))\nanswer = reducer.invoke({"partials": mapped})',
    ),
    'orchestrator-workers': PatternDemo(
        slug='orchestrator-workers',
        name='Orchestrator-Workers',
        domain='Ablauf',
        aliases=('Coordinator-Workers', 'Manager-Worker'),
        idea='Ein Orchestrator zerlegt Arbeit dynamisch und verteilt Teilaufgaben an Worker.',
        frameworks=('LangGraph', 'Anthropic Cookbook', 'Google ADK'),
        steps=('Teilaufgaben erkennen', 'Worker pro Teilaufgabe starten', 'Antworten zentral aggregieren'),
        snippet='tasks = orchestrator.invoke({"goal": prompt})\nresults = [workers[task.kind].invoke(task) for task in tasks]\nanswer = orchestrator.invoke({"goal": prompt, "results": results})',
    ),
    'parallelization-sectioning': PatternDemo(
        slug='parallelization-sectioning',
        name='Parallelization (Sectioning)',
        domain='Ablauf',
        aliases=('Sectioning', 'Fan-out by Segment'),
        idea='Unabhängige Segmente werden parallel verarbeitet und danach zusammengeführt.',
        frameworks=('LangGraph', 'LangChain RunnableParallel'),
        steps=('Input in Segmente teilen', 'Segmente parallel bearbeiten', 'Ergebnisse konsolidieren'),
        snippet='sections = split_into_sections(prompt)\npartial = RunnableParallel({s.id: worker for s in sections}).invoke(sections)\nanswer = reducer.invoke(partial)',
    ),
    'parallelization-voting': PatternDemo(
        slug='parallelization-voting',
        name='Parallelization (Voting)',
        domain='Ablauf',
        aliases=('Voting', 'Ensemble Voting'),
        idea='Mehrere Läufe bearbeiten dieselbe Aufgabe und ein Aggregator wählt das beste Ergebnis.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Drei Kandidaten generieren', 'Kandidaten bewerten', 'Gewinner oder Synthese zurückgeben'),
        snippet='candidates = [chain.invoke(prompt) for _ in range(3)]\nscores = judge.batch(candidates)\nanswer = candidates[max(range(len(scores)), key=scores.__getitem__)]',
    ),
    'plan-and-execute': PatternDemo(
        slug='plan-and-execute',
        name='Plan-and-Execute',
        domain='Denken',
        aliases=('Planner-Executor', 'Plan then Act'),
        idea='Ein Agent erstellt zuerst einen Plan und arbeitet die Schritte danach kontrolliert ab.',
        frameworks=('LangGraph', 'LangChain', 'OpenAI Agents SDK'),
        steps=('Plan mit drei Teilaufgaben erzeugen', 'Jeden Schritt mit explizitem Zwischenergebnis ausführen', 'Finale Antwort aus Plan und Ergebnissen zusammensetzen'),
        snippet='plan = planner.invoke({"goal": prompt})\nfor step in plan.steps:\n    observations.append(executor.invoke({"step": step}))\nfinal = synthesizer.invoke({"plan": plan, "observations": observations})',
    ),
    'rewoo': PatternDemo(
        slug='rewoo',
        name='ReWOO',
        domain='Denken',
        aliases=('Reasoning without Observation', 'Planner-Solver'),
        idea='Der Agent plant Tool-Aufrufe vorab und löst erst nach gebündelter Beobachtung die Aufgabe.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Tool-Bedarf aus dem Prompt ableiten', 'Unabhängige Tool-Aufrufe gesammelt ausführen', 'Solver fasst alle Beobachtungen in einem finalen Schritt zusammen'),
        snippet='tool_plan = ["search_docs", "read_examples", "summarize_constraints"]\nobservations = {tool: tools[tool].invoke(prompt) for tool in tool_plan}\nanswer = solver.invoke({"prompt": prompt, "observations": observations})',
    ),
    'self-consistency': PatternDemo(
        slug='self-consistency',
        name='Self-Consistency',
        domain='Denken',
        aliases=('Sample-and-Vote', 'Consensus Sampling'),
        idea='Mehrere unabhängige Antworten werden erzeugt und per Konsens zusammengeführt.',
        frameworks=('LangChain', 'LangGraph'),
        steps=('Mehrere unabhängige Samples mit leicht unterschiedlicher Perspektive erzeugen', 'Antworten normalisieren und gruppieren', 'Mehrheits- oder Konsensantwort zurückgeben'),
        snippet='samples = [model.invoke(prompt) for _ in range(5)]\nwinner = majority_vote(normalize(sample) for sample in samples)\nreturn winner',
    ),
    'tree-of-thoughts': PatternDemo(
        slug='tree-of-thoughts',
        name='Tree of Thoughts',
        domain='Denken',
        aliases=('ToT', 'Branching Reasoning'),
        idea='Mehrere Reasoning-Pfade werden als Baum exploriert und bewertet.',
        frameworks=('LangGraph', 'LangChain'),
        steps=('Drei alternative Lösungsäste generieren', 'Jeden Ast mit einer einfachen Rubrik bewerten', 'Besten Ast weiter ausbauen und finalisieren'),
        snippet='branches = [model.invoke(f"Propose path {i}: {prompt}") for i in range(3)]\nranked = sorted(branches, key=score_branch, reverse=True)\nanswer = model.invoke(f"Continue the strongest branch: {ranked[0]}")',
    ),
    'actor-model': PatternDemo(
        slug='actor-model',
        name='Actor Model',
        domain='Systembetrieb / Runtime',
        aliases=('Agent Actors',),
        idea='Agents kapseln Zustand und kommunizieren über Nachrichten.',
        frameworks=('Ray actors', 'Microsoft Agent Framework'),
        steps=('Actor pro Agent starten', 'Nachricht senden', 'Antwort asynchron sammeln'),
        snippet='researcher.send({"task": prompt})\nreply = await researcher.receive()',
    ),
    'adapter-pattern': PatternDemo(
        slug='adapter-pattern',
        name='Adapter Pattern',
        domain='Systembetrieb / Tool Integration',
        aliases=('Tool Adapter', 'API Wrapper'),
        idea='Uneinheitliche APIs werden in stabile Agent-Tools übersetzt.',
        frameworks=('LangChain Tools', 'Custom adapters'),
        steps=('Externe API kapseln', 'Agentenfreundliches Schema definieren', 'Fehler und Auth im Adapter behandeln'),
        snippet='class TicketAdapter:\n    def create_ticket(self, title: str) -> str: ...\ntool = StructuredTool.from_function(TicketAdapter().create_ticket)',
    ),
    'audit-trail': PatternDemo(
        slug='audit-trail',
        name='Audit Trail',
        domain='Systembetrieb / Governance',
        aliases=('Execution Log', 'Decision Log'),
        idea='Entscheidungen und Tool-Aufrufe werden nachvollziehbar protokolliert.',
        frameworks=('LangSmith', 'OpenTelemetry'),
        steps=('Run-ID erzeugen', 'Events loggen', 'Trace für Review speichern'),
        snippet='audit.log("tool_call", tool=name, args=safe_args, run_id=run_id)\nresult = tool.invoke(args)',
    ),
    'capability-routing': PatternDemo(
        slug='capability-routing',
        name='Capability Routing',
        domain='Systembetrieb / Tool Integration',
        aliases=('Tool Selection', 'Skill Routing'),
        idea='Anfragen werden anhand benötigter Fähigkeiten an passende Tools geleitet.',
        frameworks=('LangGraph', 'OpenAI Agents SDK'),
        steps=('Capability aus Prompt ableiten', 'Passendes Tool-Set wählen', 'Antwort mit gewählter Capability erzeugen'),
        snippet='capability = router.invoke(prompt)\ntools = registry.by_capability(capability)\nanswer = agent.with_tools(tools).invoke(prompt)',
    ),
    'checkpointing-resumability': PatternDemo(
        slug='checkpointing-resumability',
        name='Checkpointing / Resumability',
        domain='Systembetrieb / Runtime',
        aliases=('Persistent Run State',),
        idea='Ausführungszustand wird gespeichert und später fortgesetzt.',
        frameworks=('LangGraph checkpointers', 'Deep Agents'),
        steps=('Checkpoint schreiben', 'Run unterbrechen', 'Mit gleicher Thread-ID fortsetzen'),
        snippet='config = {"configurable": {"thread_id": "demo"}}\napp.invoke(input_state, config=config)\napp.invoke(next_state, config=config)',
    ),
    'compressed-context-memory': PatternDemo(
        slug='compressed-context-memory',
        name='Compressed Context Memory',
        domain='Systembetrieb / Memory',
        aliases=('Summary Memory', 'Rolling Summary'),
        idea='Langer Verlauf wird verdichtet, damit relevante Information im Kontextfenster bleibt.',
        frameworks=('LangChain', 'LangGraph'),
        steps=('Alte Turns zusammenfassen', 'Summary mit neuen Fakten aktualisieren', 'Antwort mit verdichtetem Kontext erzeugen'),
        snippet='summary = summarizer.invoke({"old": summary, "new": recent_messages})\nanswer = agent.invoke({"summary": summary, "input": prompt})',
    ),
    'distributed-tracing': PatternDemo(
        slug='distributed-tracing',
        name='Distributed Tracing',
        domain='Systembetrieb / Observability',
        aliases=('Agent Tracing',),
        idea='Agentenläufe und Tool-Aufrufe werden als zusammenhängende Traces sichtbar.',
        frameworks=('LangSmith', 'OpenTelemetry'),
        steps=('Span pro Node erzeugen', 'Tool-Latenz erfassen', 'Trace-ID in Logs weiterreichen'),
        snippet='with tracer.span("agent.run"):\n    with tracer.span("tool.search"):\n        result = search.invoke(prompt)',
    ),
    'episodic-memory': PatternDemo(
        slug='episodic-memory',
        name='Episodic Memory',
        domain='Systembetrieb / Memory',
        aliases=('Experience Memory',),
        idea='Abgeschlossene Aufgaben werden als Episoden wiederverwendet.',
        frameworks=('LangGraph stores', 'CrewAI Memory'),
        steps=('Ähnliche Episode suchen', 'Lösungsweg adaptieren', 'Neue Episode speichern'),
        snippet='episode = store.search(prompt, kind="task_episode")\nanswer = agent.invoke({"input": prompt, "episode": episode})',
    ),
    'event-driven-choreography': PatternDemo(
        slug='event-driven-choreography',
        name='Event-driven Choreography',
        domain='Systembetrieb / Runtime',
        aliases=('Event Choreography',),
        idea='Komponenten reagieren auf Ereignisse statt auf zentrale Steuerung.',
        frameworks=('AWS EventBridge', 'LangGraph with event runtime'),
        steps=('Event publizieren', 'Subscriber reagieren', 'Folgeevents erzeugen'),
        snippet='bus.publish("task.created", {"prompt": prompt})\n# agents subscribe to task.created and emit task.completed',
    ),
    'function-calling': PatternDemo(
        slug='function-calling',
        name='Function Calling',
        domain='Systembetrieb / Tool Integration',
        aliases=('Tool Calling',),
        idea='Tools werden über strukturierte, validierbare Argumente aufgerufen.',
        frameworks=('LangChain Tools', 'OpenAI Agents SDK'),
        steps=('Schema definieren', 'Tool auswählen', 'Argumente validieren und ausführen'),
        snippet='@tool\ndef lookup_order(order_id: str) -> str: ...\nagent = create_agent(model, tools=[lookup_order])',
    ),
    'graph-memory': PatternDemo(
        slug='graph-memory',
        name='Graph Memory',
        domain='Systembetrieb / Memory',
        aliases=('Knowledge Graph Memory',),
        idea='Entitäten und Beziehungen werden als Graph gespeichert.',
        frameworks=('LangGraph with graph stores', 'Neo4j tool integration'),
        steps=('Entitäten extrahieren', 'Kanten aktualisieren', 'Antwort über Graphpfade begründen'),
        snippet='entities, edges = extractor.invoke(prompt)\ngraph.upsert(entities, edges)\nanswer = agent.invoke({"paths": graph.neighborhood(entities)})',
    ),
    'human-in-the-loop-approval-gate': PatternDemo(
        slug='human-in-the-loop-approval-gate',
        name='Human-in-the-Loop Approval Gate',
        domain='Systembetrieb / Governance',
        aliases=('HITL', 'Human Approval'),
        idea='Kritische Aktionen werden vor Ausführung menschlich freigegeben.',
        frameworks=('LangGraph interrupts', 'Google ADK'),
        steps=('Riskante Aktion erkennen', 'Freigabe anfordern', 'Nach Approval fortsetzen'),
        snippet='if action.risk == "high":\n    interrupt({"approval_required": action})\nexecute(action)',
    ),
    'integration-tests-for-agents': PatternDemo(
        slug='integration-tests-for-agents',
        name='Integration Tests für Agents',
        domain='Systembetrieb / Observability',
        aliases=('Scenario Tests', 'End-to-End Agent Tests'),
        idea='Agenten werden über realistische Szenarien mit Tools und State getestet.',
        frameworks=('pytest', 'LangSmith datasets'),
        steps=('Szenario laden', 'Agent mit Mocks ausführen', 'Trace und Output prüfen'),
        snippet='def test_refund_agent():\n    result = agent.invoke(case.input)\n    assert result.action == "request_approval"',
    ),
    'least-privilege-agent': PatternDemo(
        slug='least-privilege-agent',
        name='Least Privilege Agent',
        domain='Systembetrieb / Governance',
        aliases=('Scoped Agent',),
        idea='Jeder Agent erhält nur die Tools und Daten, die er benötigt.',
        frameworks=('OpenAI Agents SDK', 'LangGraph'),
        steps=('Rolle definieren', 'Tool-Scope begrenzen', 'Handoff nur mit minimalem Kontext'),
        snippet='billing_agent = create_agent(model, tools=billing_readonly_tools)\nanswer = billing_agent.invoke(prompt)',
    ),
    'llm-as-judge': PatternDemo(
        slug='llm-as-judge',
        name='LLM-as-Judge',
        domain='Systembetrieb / Observability',
        aliases=('Model Judge',),
        idea='Ein Modell bewertet Ausgaben anhand einer Rubrik.',
        frameworks=('LangSmith', 'OpenAI Evals'),
        steps=('Rubrik definieren', 'Antworten bewerten', 'Score für Regressionen speichern'),
        snippet='score = judge.invoke({"rubric": rubric, "answer": answer})\nmetrics.record("quality", score)',
    ),
    'mcp': PatternDemo(
        slug='mcp',
        name='MCP (Model Context Protocol)',
        domain='Systembetrieb / Tool Integration',
        aliases=('MCP-based Tool Integration',),
        idea='Tools und Ressourcen werden über MCP standardisiert eingebunden.',
        frameworks=('MCP Clients', 'LangChain adapters'),
        steps=('MCP Server verbinden', 'Capabilities entdecken', 'Tool-Aufrufe über Protokoll ausführen'),
        snippet='client = MCPClient("filesystem")\ntools = client.list_tools()\nanswer = agent.invoke({"tools": tools, "input": prompt})',
    ),
    'multimodal-guardrails': PatternDemo(
        slug='multimodal-guardrails',
        name='Multimodal Guardrails',
        domain='Systembetrieb / Governance',
        aliases=('Media Validation',),
        idea='Text, Bild, Audio oder Video werden modalitätsspezifisch geprüft.',
        frameworks=('OpenAI moderation', 'Azure AI Content Safety', 'AWS Bedrock Guardrails'),
        steps=('Input-Modalität erkennen', 'Passende Policy prüfen', 'Antwort blockieren oder erlauben'),
        snippet='policy_result = guardrail.check(media=input_asset)\nif not policy_result.allowed:\n    return policy_result.reason',
    ),
    'output-validation-schema-enforcement': PatternDemo(
        slug='output-validation-schema-enforcement',
        name='Output Validation / Schema Enforcement',
        domain='Systembetrieb / Governance',
        aliases=('Structured Output Validation',),
        idea='Modellantworten werden gegen Schema oder Regeln geprüft.',
        frameworks=('Pydantic', 'OpenAI Structured Outputs', 'LangChain'),
        steps=('Schema definieren', 'Antwort parsen', 'Bei Fehler retry oder ablehnen'),
        snippet='result = model.with_structured_output(AnswerSchema).invoke(prompt)\nAnswerSchema.model_validate(result)',
    ),
    'permission-scoped-tools': PatternDemo(
        slug='permission-scoped-tools',
        name='Permission-scoped Tools',
        domain='Systembetrieb / Tool Integration',
        aliases=('Scoped Tools',),
        idea='Tools werden mit minimalen Berechtigungen pro Agent oder Lauf bereitgestellt.',
        frameworks=('OpenAI Agents SDK', 'LangGraph'),
        steps=('Scope bestimmen', 'Tool-Liste begrenzen', 'Auditierbaren Aufruf ausführen'),
        snippet='tools = registry.for_scope(user_scope="read_only")\nagent = create_agent(model, tools=tools)',
    ),
    'pub-sub-agent-mesh': PatternDemo(
        slug='pub-sub-agent-mesh',
        name='Pub/Sub Agent Mesh',
        domain='Systembetrieb / Runtime',
        aliases=('Agent Mesh',),
        idea='Agents kommunizieren lose gekoppelt über Topics oder Busse.',
        frameworks=('Kafka', 'Redis Streams', 'AWS SNS/SQS'),
        steps=('Topic definieren', 'Agents abonnieren', 'Nachrichten fan-out/fan-in verarbeiten'),
        snippet='bus.subscribe("research.requests", researcher)\nbus.publish("research.requests", {"prompt": prompt})',
    ),
    'saga-compensation': PatternDemo(
        slug='saga-compensation',
        name='Saga / Compensation',
        domain='Systembetrieb / Runtime',
        aliases=('Compensating Action',),
        idea='Mehrschrittige Aktionen werden durch fachliche Rücknahme-Schritte abgesichert.',
        frameworks=('Workflow Engines', 'LangGraph durable runtime'),
        steps=('Aktion ausführen', 'Fehler erkennen', 'Kompensation auslösen'),
        snippet='try:\n    reserve(); charge(); notify()\nexcept StepFailed:\n    refund(); release_reservation()',
    ),
    'sandbox-execution': PatternDemo(
        slug='sandbox-execution',
        name='Sandbox Execution',
        domain='Systembetrieb / Governance',
        aliases=('Isolated Execution',),
        idea='Code oder Aktionen laufen isoliert mit begrenzten Rechten.',
        frameworks=('OpenAI sandboxed tools', 'Docker', 'E2B'),
        steps=('Code prüfen', 'Sandbox mit Limits starten', 'Output ohne Seiteneffekte auswerten'),
        snippet='result = sandbox.run(code, timeout=5, network=False)\nanswer = explain(result)',
    ),
    'semantic-memory': PatternDemo(
        slug='semantic-memory',
        name='Semantic Memory',
        domain='Systembetrieb / Memory',
        aliases=('Knowledge Memory',),
        idea='Dauerhaftes Wissen wird unabhängig von Gesprächen abgelegt.',
        frameworks=('LangChain', 'OpenAI Vector Stores'),
        steps=('Fakten extrahieren', 'Wissen validieren', 'Wissen abrufbar speichern'),
        snippet='facts = extractor.invoke(prompt)\nknowledge_store.upsert(facts)\nanswer = agent.invoke({"facts": knowledge_store.search(prompt)})',
    ),
    'token-cost-tracking': PatternDemo(
        slug='token-cost-tracking',
        name='Token / Cost Tracking',
        domain='Systembetrieb / Observability',
        aliases=('Usage Tracking',),
        idea='Token und Kosten werden pro Run, Agent oder Workflow gemessen.',
        frameworks=('LangSmith', 'Provider Usage APIs'),
        steps=('Usage aus Response lesen', 'Kosten berechnen', 'Budgetentscheidung treffen'),
        snippet='usage = response.usage_metadata\ncosts.add(run_id, tokens=usage["total_tokens"])',
    ),
    'tool-registry': PatternDemo(
        slug='tool-registry',
        name='Tool Registry',
        domain='Systembetrieb / Tool Integration',
        aliases=('Capability Catalog',),
        idea='Tools werden mit Schema, Beschreibung und Berechtigungen katalogisiert.',
        frameworks=('LangChain', 'LangGraph'),
        steps=('Tools registrieren', 'Metadaten pflegen', 'Agent erhält passenden Ausschnitt'),
        snippet='registry.add(tool, scopes=["read:docs"], owner="docs-team")\ntools = registry.for_task(prompt)',
    ),
    'vector-memory': PatternDemo(
        slug='vector-memory',
        name='Vector Memory',
        domain='Systembetrieb / Memory',
        aliases=('Embedding Memory', 'RAG Memory'),
        idea='Embedding-Suche ruft semantisch ähnliche Inhalte ab.',
        frameworks=('LangChain VectorStores', 'OpenAI Vector Stores'),
        steps=('Dokumente embedden', 'Top-k Treffer abrufen', 'Antwort mit Retrieval-Kontext erzeugen'),
        snippet='docs = vector_store.similarity_search(prompt, k=4)\nanswer = rag_chain.invoke({"context": docs, "question": prompt})',
    ),
    'workflow-dag-durable-execution': PatternDemo(
        slug='workflow-dag-durable-execution',
        name='Workflow DAG / Durable Execution',
        domain='Systembetrieb / Runtime',
        aliases=('Durable Workflow',),
        idea='Workflows laufen als persistenter Graph mit Retry und Wiederaufnahme.',
        frameworks=('LangGraph', 'Temporal', 'AWS Strands Workflow'),
        steps=('DAG definieren', 'State persistieren', 'Fehlerhafte Nodes retryen'),
        snippet='workflow.add_edge("extract", "transform")\nworkflow.add_edge("transform", "load")\napp = workflow.compile(checkpointer=checkpointer)',
    ),
    'working-memory': PatternDemo(
        slug='working-memory',
        name='Working Memory / Scratchpad',
        domain='Systembetrieb / Memory',
        aliases=('Scratchpad', 'Task State'),
        idea='Kurzfristiger Arbeitszustand hält Zwischenschritte eines Laufs.',
        frameworks=('LangGraph State', 'OpenAI Agents SDK'),
        steps=('State initialisieren', 'Tool-Ergebnisse in State schreiben', 'Finale Antwort aus State erzeugen'),
        snippet='state = {"scratchpad": [], "input": prompt}\nstate["scratchpad"].append(tool.invoke(prompt))\nanswer = agent.invoke(state)',
    ),
    'agents-as-tools': PatternDemo(
        slug='agents-as-tools',
        name='Agents-as-Tools',
        domain='Zusammenarbeit',
        aliases=('Callable Agents', 'Specialist-as-Tool'),
        idea='Ein Hauptagent ruft spezialisierte Agents über stabile Tool-Schnittstellen auf.',
        frameworks=('AWS Strands', 'OpenAI Agents SDK', 'LangGraph'),
        steps=('Spezialisten als Tools registrieren', 'Hauptagent wählt Tool anhand Aufgabe', 'Spezialist liefert begrenztes Ergebnis'),
        snippet='tools = [research_agent.as_tool(), code_agent.as_tool()]\nmain_agent = create_agent(model, tools=tools)\nanswer = main_agent.invoke({"messages": [{"role": "user", "content": prompt}]})',
    ),
    'blackboard': PatternDemo(
        slug='blackboard',
        name='Blackboard',
        domain='Zusammenarbeit',
        aliases=('Shared Workspace', 'Shared State Coordination'),
        idea='Agents koordinieren indirekt über eine gemeinsame Zustandsfläche.',
        frameworks=('LangGraph', 'AWS Strands'),
        steps=('Shared State initialisieren', 'Agents lesen und schreiben Hypothesen', 'Synthesizer liest finalen Zustand'),
        snippet='blackboard["goal"] = prompt\nfor agent in agents:\n    blackboard.update(agent.invoke(blackboard))\nanswer = synthesizer.invoke(blackboard)',
    ),
    'contract-net': PatternDemo(
        slug='contract-net',
        name='Contract Net',
        domain='Zusammenarbeit',
        aliases=('Task Bidding', 'Contract Net Protocol'),
        idea='Agents bieten auf ausgeschriebene Aufgaben und der beste Anbieter erhält den Auftrag.',
        frameworks=('LangGraph custom protocol', 'AutoGen / AG2 custom conversation'),
        steps=('Aufgabe ausschreiben', 'Bids mit Fähigkeit und Kosten sammeln', 'Gewinner beauftragen'),
        snippet='bids = [agent.bid(task) for agent in agents]\nwinner = min(bids, key=lambda bid: (bid.cost, -bid.confidence))\nresult = winner.agent.invoke(task)',
    ),
    'group-chat': PatternDemo(
        slug='group-chat',
        name='Group Chat',
        domain='Zusammenarbeit',
        aliases=('Multi-Agent Chat', 'Shared Conversation'),
        idea='Mehrere Agents kommunizieren in einem gemeinsamen Gesprächsraum.',
        frameworks=('AutoGen / AG2', 'Microsoft Agent Framework'),
        steps=('Rollen initialisieren', 'Beiträge round-robin sammeln', 'Moderator fasst Ergebnis zusammen'),
        snippet='messages = [user_message(prompt)]\nfor agent in [researcher, critic, builder]:\n    messages.append(agent.invoke(messages))\nanswer = moderator.invoke(messages)',
    ),
    'hierarchical-supervisor': PatternDemo(
        slug='hierarchical-supervisor',
        name='Hierarchical Supervisor',
        domain='Zusammenarbeit',
        aliases=('Manager Hierarchy', 'Hierarchical Teams'),
        idea='Supervisoren koordinieren Subteams und verdichten Ergebnisse nach oben.',
        frameworks=('LangGraph', 'CrewAI'),
        steps=('Top-Level-Ziel an Team-Supervisor geben', 'Subteams arbeiten unabhängig', 'Top-Level-Supervisor aggregiert'),
        snippet='frontend_plan = frontend_supervisor.invoke(prompt)\nbackend_plan = backend_supervisor.invoke(prompt)\nfinal = lead_supervisor.invoke({"frontend": frontend_plan, "backend": backend_plan})',
    ),
    'market-based': PatternDemo(
        slug='market-based',
        name='Market-based',
        domain='Zusammenarbeit',
        aliases=('Price-based Coordination', 'Auction-based Agents'),
        idea='Agents priorisieren Arbeit über Budgets, Preise oder Nutzenfunktionen.',
        frameworks=('LangGraph custom coordination', 'AWS Strands custom workflow'),
        steps=('Budget und Nutzen je Aufgabe bestimmen', 'Agents bieten Kapazität an', 'Marktregel verteilt Aufgaben'),
        snippet='market = Market(budget=100)\nallocations = market.clear(tasks, agent_offers)\nresults = [allocation.agent.invoke(allocation.task) for allocation in allocations]',
    ),
    'multi-agent-debate': PatternDemo(
        slug='multi-agent-debate',
        name='Multi-Agent Debate',
        domain='Zusammenarbeit',
        aliases=('Debate', 'Adversarial Agents'),
        idea='Agents prüfen eine Entscheidung aus gegensätzlichen Perspektiven.',
        frameworks=('AutoGen / AG2', 'LangGraph'),
        steps=('Pro- und Contra-Agent erzeugen', 'Argumente austauschen', 'Judge entscheidet anhand Rubrik'),
        snippet='pro = pro_agent.invoke(prompt)\ncontra = contra_agent.invoke(prompt)\nverdict = judge.invoke({"pro": pro, "contra": contra, "rubric": rubric})',
    ),
    'swarm': PatternDemo(
        slug='swarm',
        name='Swarm',
        domain='Zusammenarbeit',
        aliases=('Peer Agent Swarm', 'Decentralized Agents'),
        idea='Agents koordinieren sich dezentral über lokale Regeln und geteilte Ziele.',
        frameworks=('LangGraph Swarm', 'AWS Strands'),
        steps=('Ziel in gemeinsamen Raum stellen', 'Peers schlagen nächste Aktionen vor', 'Stoppen, wenn Konsens oder Budget erreicht ist'),
        snippet='while budget.remaining:\n    proposals = [agent.propose(shared_state) for agent in peers]\n    shared_state = apply_best_local_moves(shared_state, proposals)',
    ),
}


def get_spec(slug: str) -> PatternDemo:
    return SPECS[slug]


def get_pattern(slug: str) -> PatternDemo:
    return SPECS[slug]
